### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by cycyrild** [zuozishi/MediaSession.Blazor#1]
Hello, I have a problem when loading the module from a page other than the root of the site.
The application tries to import the script from the relative path of the page and not from the root.
I already tried to add this line "app.UsePathBase("/");" but nothing helps.
How can I force the import of the script from the root of the site?
<img width="635" alt="img" src="https://user-images.githubusercontent.com/42033203/177058133-6c4b587d-5b33-4c46-a6cf-c13fb8340949.png">

**Comment by zuozishi** [comment]
https://github.com/zuozishi/MediaSession.Blazor/blob/294b5cc4252ad4e4a71b95161a93205e7ef4f582/MediaSession.Blazor/Components/MediaSession.cs#L14

I think the problem in here.
